apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1 # how many instances of the voting app
  selector: # after it creates pod, which pods shoult it watch over
    matchLabels:
      app: worker
  template: # what pod are you interested in creating
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker